version: 0.2

env:
  variables:
    TF_VERSION: "0.14.6"
        
phases:
  install:
    on-failure: ABORT
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "/usr/bin/sudo apt-get install tree"
      - "tree -f"
  build:
    on-failure: ABORT
    commands:
      - terraform init
      - terraform plan
  post_build:
    on-failure: ABORT
    commands:
      - terraform apply -auto-approve
